splitio/redux-client

README.md
package-lock.json
package.json

Updating README and version

---

package-lock.json
package.json

Updating SDK version

---

CHANGES.txt
package-lock.json
package.json
src/__tests__/utils.test.ts
src/actions.ts
src/asyncActions.ts
src/constants.ts
src/utils.ts

- Bug fix: support other types for user keys, besides strings and objects with matchingKey.
- The function `matching` was added to handle keys.
- Updated JS SDK dependency and others to fix vulnerabilities.
- Unit tests for `matching` function

Bug fix and update dependencies

---

CHANGES.txt
package-lock.json
package.json
src/__tests__/actions.browser.test.ts
src/__tests__/actions.node.test.ts
src/__tests__/utils.test.ts
src/asyncActions.ts
src/utils.ts

- Updated `initSplitSdk` ready promise using a new promise util.
- unit tests and integration tests

`initSplitSdk` ready promise

---

CHANGES.txt
package-lock.json
package.json

- Updated JS SDK dependency to version 10.13.0, which provides streaming synchronization by default.

Updated JS SDK version to 10.13.0

---

CHANGES.txt
package-lock.json
package.json

Update version and changelog for release

Prepare for release v1.2.0

---

CHANGES.txt
package-lock.json
package.json

Updating JS version

---

package-lock.json
package.json

Updated the SDK version to 10.15.0
Run the tests and run an app.

Development into master - Updating to JS 10.15.0

---

CHANGES.txt
package-lock.json
package.json

Release v1.3.0

---

CHANGES.txt
README.md
package-lock.json
package.json

Update Split SDK version to catch up with the latest changes.

Patch: update Splitio package version

---

.github/workflows/ci.yml

GHA CI workflow: build condition fixed

---

CHANGES.txt
package-lock.json
package.json
src/__tests__/utils/mockBrowserSplitSdk.ts
src/__tests__/utils/mockNodeSplitSdk.ts
src/asyncActions.ts
src/utils.ts

Updates to use JS SDK v10.18

---

package.json

Update package.json files list

---

CHANGES.txt

Update release date on changes file

---

.gitignore
CHANGES.txt
package-lock.json
package.json
tsconfig.json

Prepare release v1.7.0

---

CHANGES.txt
README.md

[SDKS-6946][DW] Update CHANGES & README files

---

src/constants.ts
types/constants.d.ts

[SDKS-6943][DW] Update constants file

---

src/reducer.ts

[SDKS-6944][DW] Update reducer

---

src/__tests__/actions.node.test.ts
src/__tests__/helpers.browser.test.ts
src/__tests__/helpers.node.test.ts
src/__tests__/utils/mockBrowserSplitSdk.ts
src/__tests__/utils/mockNodeSplitSdk.ts
src/asyncActions.ts
src/react-redux/connectToggler.ts
src/selectors.ts
src/types.ts
types/asyncActions.d.ts
types/helpers.d.ts
types/react-redux/connectToggler.d.ts
types/selectors.d.ts
types/types.d.ts

[SDKS-6945][DW] Replace splitName with featureFlagName

---

README.md
src/__tests__/actions.browser.test.ts
src/__tests__/actions.node.test.ts
src/__tests__/helpers.node.test.ts
src/__tests__/reducer.test.ts
src/__tests__/selectors.test.ts
src/__tests__/utils/sdkConfigs.ts
src/asyncActions.ts
src/helpers.ts
src/types.ts
types/helpers.d.ts
types/types.d.ts

[SDKS-6956][DW] Replace splits, splitName, webConsole and apiKey

---

src/react-redux/connectToggler.ts
types/react-redux/connectToggler.d.ts

[SDKS-6963] Use feature flag instead of featureFlag

---

README.md

[DW] update readme apiKey -> sdkKey

---

.eslintrc.js

Update `prefer-const` linter rule

---

.github/workflows/ci.yml
.github/workflows/update-license-year.yml

Update CI/CD configuration

---

CHANGES.txt
package-lock.json
package.json
src/index.ts
src/types.ts
types/index.d.ts
types/types.d.ts

Prepare release v1.8.0

---

CHANGES.txt
package-lock.json
package.json

Release 1.9.0

---

CHANGES.txt
package-lock.json
package.json
src/__tests__/actions.browser.test.ts
src/__tests__/actions.node.test.ts
src/__tests__/utils/mockBrowserSplitSdk.ts
src/__tests__/utils/mockNodeSplitSdk.ts
src/asyncActions.ts
types/asyncActions.d.ts

[Flag sets] Implementation

---

CHANGES.txt
package-lock.json
package.json

Semver matchers & Flags spec query param

---

CHANGES.txt
package-lock.json
package.json

Improve Proxy fallback handling. 
Related to https://github.com/splitio/split-synchronizer/issues/315

Prepare release v2.2.1

---

CHANGES.txt
README.md
package-lock.json
package.json
src/helpers.ts
src/selectors.ts
src/types.ts

Prepare release v2.3.0
